field.value.dt70_rgb_selector:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.dt70_rgb_selector:
  type: mapping
  label: rgb_selector widget settings
  mapping:
    foo:
      type: string
      label: Foo
